spring.application.name=devunion-backend

# DataSource ?? (Docker ???? ??)
spring.datasource.url=jdbc:postgresql://localhost:5432/devunion
spring.datasource.username=devu
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate ??
# ???: ??? ?? ? DB ??? ?? ???? (?? ?: none)
spring.jpa.hibernate.ddl-auto=update
# ???? SQL ?? ?? ??
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true # SQL ?? ???

# ?? ?? (?? ??: ??? JPA ??)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE